AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  ScrapeData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/telescope
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
        AutoPopulateEvent:
            Type: Schedule
            Properties:
              Schedule: rate(1 minute)
  ViewData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/lens
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post